// Code generated by "esc -o cmd/gangway/bindata.go templates/"; DO NOT EDIT.

package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	return nil, nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/templates/commandline.tmpl": {
		local:   "templates/commandline.tmpl",
		size:    4223,
		modtime: 1537905632,
		compressed: `
H4sIAAAAAAAC/7RYW1fbuBZ+51fs8XStaRdVFCi39sQ5Jw3QpoWGklAKax5GlndsEVkykpwLPfz3s+TE
XEKgrDOdlwRt+dvf/vbFUmj8tttt98+O9iB1mWyuNPwXSKaSMEAVeAOyuLkC0MjQMUidywleFmIUBm2t
HCpH+tMcA+CzVRg4nDjq3fwLeMqMRRee9PfJTkBv3SiWYRiMBI5zbdwd8FjELg1jHAmOpFy8BqGEE0wS
y5nEcO01ZGwisiKrDLX63LUTTmLzA1PJmE0bdLZc8Tu/EQLtXg+AkPJJKdQQUoODMPCK7DtKB1o5W0u0
TiSyXNga1xkVXKt/D1gm5DQ8ZA6NYHK1w7WyARiUYWDdVKJNEV1w63hxZ4GJx+rC1rjURTyQzGDJxC7Y
hEoRWZrNecQV0nptrV6vrVNu79lrmVA1bm0wVweEwJERNqv0WW5E7sAa/mza3OPpWm1to1afLUqWCxuA
UA4TI9w0DGzK1je3yEX/w9VB67Lb4t2D1dbB7vpg3Y32z7YHdiseD7uod3Ymovj2kR0PwwC40dZqIxKh
woApraaZLmzQbNBZnL8kZK6zXCtUbm4nEbPpExLa6aYZbbqkFX87bKfbp5dR/aTLvw+/tj5+2e/hlVit
j2j9amsyGD9Xwi8o/j1JLsUMKzlOZ9oYPb6p/RJNG723xeDYrO1dspP9fTx8SzfXP3zc2vlo13rRaLKD
+9/fn+Zy5+qo87gmoP+ImFwWiVCWOq1lxMyNqnL1lKjJ2TbtnbDtrbemfnS+NnXnR/sX66eXqnt+xs56
n6Pva+m3vvgqeeunov72XPxUxPJm644+n3064GfHR2/OO0dC9utvzFRNzwfD+MP++Ko9PtlZ//J+g7b6
G89pNoD/UwyXIo80M3HtwtL1Wt3PzY1pHv6vHcsqY1znU+I0uaGb5+6B/Yks2tXzNfv+5Os+Y+PtCbbU
aUR1byd5f7hxuPdZ7J0eHn+q56t0EvFnjWyDVocbQCPS8XT2Z/lR2hQbAZfM2jCQIkkdiWSB4D8CMFpi
GCg2EglzQqugeYMrsbG4wSo2ImPD8hxNedIxodAEzQYDEYeB1Ikmt+b5iP0eVOjIMBUT/1TQTKqzjS2w
FbJ63PhAIRUxEq1IhjHx8FiPFyMscVL4MGaU1HMULmgelN+epEGlWGCihSxPnfvkXoiXmelISLyJ3fow
FBv9jPr3oLmLXMcIn077TxHfs9yiIWaOEcadGDGHdmksUeGcVoRrKVluMWg2RLVVHa1ElEd7M0NVNKho
PswzjcXo1tSgit1Zriwr/p2C33eVblSP+C70rYHKoYGYmSEq8mZJzk5Rcp0h/PgBtROLxl+j4Pq6thBj
urFItfnQV0eBNp7WaUjQAddZVjaaUAiMc7TWb7l0RteWhXVovswY4XMRoVHo0AKf7byGqS5gLKQEhRh7
LNdqIJLCIHRzVJ1daGulkDt42e3stl8BK1yKSvByfmCgjXdhgEuByj0QtdlclHD/icgsqM4fiu6neC/0
u5oLJ6Rw09cwLCLkTvp75hQiBKGsY1JiDFIMEax+txDaDdG9uWjkBhciaJQtXr1RmEoKlmB5UQmaKy+A
F0YCOehC9aK1ThuW4OKtdHijgBiUyCzS6vuvmQ/7N1xYxyKJNTdxf9FIKPriZVH22X+BjYfwx4/cCOXA
aanHaF6+qL+6/uMVZVm8tUHnmfNS0kzHsDqB2h2jLWIN2ejWBrSwhkrNmSypKjMspI36vN3LZYM+yO6y
encVx6qeIOxtKWfd6guME+SFw7LRB1pKPRYqedegUfOxKj9a3p8UGHmqIbgzTO0WXF8H8Cc0gTPycMpq
OWYrVfSzYQKLjswnbtlcEmLRjNCEfq911OmVq5Pjg9kmR+PEwE8cEj99ujxfHyUHQjCLMC5xdmkoBmNU
/ueZXXwr/WdJePBnmTFSkpPc6JGI0YRaxPyRPcJMEoo4J8LaAg0pjCy1dcrlXNgT0NnLhIg4nIXjV53d
54EscoPuDrBXGjz4cazBgUGbEqeHqErs8czS94ansSK+A+vsVoilife/mCdueQ/MGyRculnY+c5exoRc
4r6w+IT7hZZfMpuLw3nn0GzQ2TWrQWf/bvhfAAAA//9IJUPgfxAAAA==
`,
	},

	"/templates/home.tmpl": {
		local:   "templates/home.tmpl",
		size:    2088,
		modtime: 1520372473,
		compressed: `
H4sIAAAAAAAC/4xWUW/jNgx+76/g6V42LLKbuxXYcnaGrd2AYnfrgHYH7JGWGZutLPkkOW5u2H8fJMdJ
mhuwBUgsUhT5kR9ppXh1c3f98OfvP0MbOr2+KOIDNJqmFGREVBDW6wuAoqOA0IbQS/o08LYU19YEMkE+
7HoSoCapFIGeQx7dvAPVovMUyj8efpHfifzoxmBHpdgyjb114eTwyHVoy5q2rEgmYQFsODBq6RVqKpcL
6PCZu6GbFdnl3nXgoGndoGlG3BX5JF7EnVdSwvX9PYCUyVKzeYLW0aYUMSO/yvONNcFnjbWNJuzZZ8p2
OStrfthgx3pXfsBAjlF/c6us8QIc6VL4sNPkW6Igjo7Pd84iqdo8+kxpO9QbjY5SJHzE51xz5fNuH4c/
U36ZLS8vsze58i/0WccmU95PMVOkuALoHWUV+hb+SmL8VKieGmcHU0tltXUrqDSqp3cHg7329bffb6q3
V0d9LIj0/JlW4DvU+mxnqsoKrq3xVqNffLAGlV28HxTXuFfT4j1X5DCwNfDBGru4oUf8OMA9Gj8pfuLg
gyPs4CM5PNm4toNjcvAbjQvorLG+R0VHFHZLbqPtuAIcgj3qR+tqOTrsV2Cs6/AE+NhyIJn8rGKtpp2/
L9Iji2TLSlv1tC9fj3XNplnBJSyv+ufZ+tw4m5mRUelPan9SQjYtOQ6zjyLfs1bk04AVla13iU6DW1Aa
vS+F5qYNstIDQfwR4KymUhjccpNqKibai5oPZwxuU/Y9uTRWyIacWBcIXJdC28bKo3rfma/FfLpyaGoZ
rcRxkHC9z6gY9GzoIjRouSZpjeyolvFgbceIaTbPB30UBp0QRHydrVjTIaiPXgxuz0/u13hEWWNAiSrw
FgP5f3VWDSFYE3tdY+9JrAuet17yJNYdmaHIeX3IsMhr3iYScoPT4qSynlTqY2Nlj7WsbBApIzY1PcsK
TSr0F4SckDBnVLl1/M5iu5xtYy9E3sgEclCjeyIj3x6ogF+HipyhQB5+HEJLJrBKjVDk7fLg7yS4s+Pe
2yF6DHh1HtBq8Ms3kBpOrB9a9jAE1hx2MLLW0JLuYWeHOGtzWIKRQxu17hSY0oOP6NMmGrjrydzexBeC
IRXgq7vbm+uvIU5uBvfcGGADwUJDAXxAF6jOiry9OmQzc/L/UpubJde2YSMmhmJbahs5S81x7JVgpEbX
EIy4JS9ps4kQJyHVYpq7dcJ5a05H4QWsmdDzLkqLqD3cQnCvHPfB7y8inyTwTp3cD7am7PHTQG6XroZp
Kd9ky2yZ3vyPXqyLfDr6hZfHlzfFf9nGy/XMKCGfXkdFPv0tuPgnAAD//yEDNLMoCAAA
`,
	},

	"/": {
		isDir: true,
		local: "",
	},

	"/templates": {
		isDir: true,
		local: "templates",
	},
}
